language: ruby
dist: trusty
cache: bundler
rvm:
  - 2.5.1
services:
  - postgresql
before_install:
  - gem install bundler
  - bundler --version
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
