# config/settings.yml for rails-settings-cached
defaults: &defaults
  homepage_hardcoded: false
  search_in_footer: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
