#!/bin/sh
# Usage: script/setup

set -e

script/bootstrap

echo "==> Turning on postgresql"
brew services start postgresql
if ! pg_ctl -D /usr/local/var/postgres status; then
  echo "failed to start postgresql"
  echo "check error logs /usr/local/var/log/postgres.log"
  echo "If error is 'The data directory was initialized by PostgreSQL version x.x, which is not compatible with this version x.x.' run 'brew postgresql-upgrade-database'"
  exit 1
fi

echo "==> Setting up databases"
bin/rake db:drop
bin/rake db:setup
