#!/bin/sh
# Usage: script/setup

set -e

script/bootstrap

set -x

echo "==> Turning on postgresql"
echo "If fails to turn on check error logs /usr/local/var/log/postgres.log"
echo "If error is 'The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 12.1.' run 'brew postgresql-upgrade-database'"
brew services start postgresql

echo "==> Setting up databases"
bin/rake db:drop
bin/rake db:setup
